### ISSUE TITLE
В колонці Тип Нерухомості групувати нерухомість

### ISSUE THREAD

**Issue by ivan-smrnk** [redexp/declarations#3]
В колонці Тип Нерухомості групувати нерухомість за трьома категоріями: Нерухомість (сюди йде усе, крім Землі і Незавершеного будівництва), Земельні ділянки, Незавершене будівництво.

**Comment by redexp** [comment]
@ivan-smrnk под группировкой ты имеешь ввиду сортировку?

**Comment by ivan-smrnk** [comment]
Так як ти реалізував у v.1.3 - ок.
