### ISSUE TITLE
 В автомобілях не підтягує вказану ціну для деяких (2019 - майже усіх) автомобілів

### ISSUE THREAD

**Issue by ivan-smrnk** [redexp/declarations#6]
![Screenshot_155](https://user-images.githubusercontent.com/73116319/96454120-137cca00-1224-11eb-8abe-e5f1ae097126.png)

**Comment by redexp** [comment]
@ivan-smrnk цен нету в декларации. Закрываем баг?

**Comment by ivan-smrnk** [comment]
yup
